import desktopPackage from "../../package.json";

export const DESKTOP_APPLICATION_NAME = desktopPackage.productName;
export const DESKTOP_APPLICATION_ID = desktopPackage.appId;
export const LEGACY_DESKTOP_USER_DATA_DIRECTORY = "AiCRM Desktop";

export const DEFAULT_API_BASE_URL = "http://127.0.0.1:16178";
export const DEFAULT_WEB_URL = "https://kyaicrm.entai.im";

export const IPC_CHANNELS = {
  apiRequest: "api:request",
  appGetConfig: "app:get-config",
  appGetVersion: "app:get-version",
  sessionLoad: "session:load",
  sessionSave: "session:save",
  sessionClear: "session:clear",
  windowGetState: "window:get-state",
  windowMinimize: "window:minimize",
  windowToggleMaximize: "window:toggle-maximize",
  windowSetFullScreen: "window:set-full-screen",
  windowSetAlwaysOnTop: "window:set-always-on-top",
  windowMoveBy: "window:move-by",
  windowOpenDevTools: "window:open-devtools",
  windowClose: "window:close",
  windowStateChanged: "window:state-changed",
  matrixAccountGetCapabilities: "matrix-account:get-capabilities",
  matrixAccountStartLogin: "matrix-account:start-login",
  matrixAccountOpenAccount: "matrix-account:open-account",
  matrixAccountCheckSession: "matrix-account:check-session",
  matrixAccountClearProfile: "matrix-account:clear-profile",
  matrixAccountLoginStateChanged: "matrix-account:login-state-changed",
  matrixAccountCreateWebSpaceLogin: "matrix-account:create-web-space-login",
  matrixAccountOpenWebSpace: "matrix-account:open-web-space",
  matrixAccountDetectWebSpaceAccount: "matrix-account:detect-web-space-account",
  matrixAccountClearWebSpace: "matrix-account:clear-web-space",
  matrixAccountWebSpaceStateChanged: "matrix-account:web-space-state-changed",
  matrixAccountCaptureWebSpaceSnapshot: "matrix-account:capture-web-space-snapshot",
  matrixAccountRunWebSpaceLoginScript: "matrix-account:run-web-space-login-script",
  matrixAccountStartOnboarding: "matrix-account:start-onboarding",
  matrixAccountGetOnboarding: "matrix-account:get-onboarding",
  matrixAccountGetOnboardingQrCode: "matrix-account:get-onboarding-qr-code",
  matrixAccountRefreshOnboardingQrCode: "matrix-account:refresh-onboarding-qr-code",
  matrixAccountCancelOnboarding: "matrix-account:cancel-onboarding",
  matrixAccountOnboardingEvent: "matrix-account:onboarding-event",
  matrixAccountSealSessionSnapshot: "matrix-account:seal-session-snapshot",
  matrixAccountVerifySessionSnapshot: "matrix-account:verify-session-snapshot",
  matrixAccountRestoreSessionSnapshot: "matrix-account:restore-session-snapshot",
  matrixAccountCleanupSessionWebSpace: "matrix-account:cleanup-session-web-space",
  aiExecutorOpenTerminalWindow: "ai-executor:open-terminal-window",
  codexExecutorAuthorize: "codex-executor:authorize",
  codexExecutorGetAuthStatus: "codex-executor:get-auth-status",
  codexAuthorizationGetCapabilities: "codex-authorization:get-capabilities",
  codexAuthorizationStart: "codex-authorization:start",
  codexAuthorizationGetSnapshot: "codex-authorization:get-snapshot",
  codexAuthorizationCancel: "codex-authorization:cancel",
  codexAuthorizationReopen: "codex-authorization:reopen",
  codexAuthorizationVerify: "codex-authorization:verify",
  codexAuthorizationCheckReadiness: "codex-authorization:check-readiness",
  codexAuthorizationGetModelCatalog: "codex-authorization:get-model-catalog",
  codexAuthorizationRefreshModelCatalog: "codex-authorization:refresh-model-catalog",
  codexAuthorizationLogout: "codex-authorization:logout",
  codexAuthorizationChanged: "codex-authorization:changed",
  desktopDeviceGetIdentity: "desktop-device:get-identity",
  desktopDeviceEnsureRegistration: "desktop-device:ensure-registration",
  desktopDeviceGetRegistrationState: "desktop-device:get-registration-state",
  desktopDeviceResetRegistrationRecovery: "desktop-device:reset-registration-recovery",
  networkLogSnapshot: "network-log:snapshot",
  networkLogClear: "network-log:clear"
} as const;
